language:
- python
python:
- '2.7'
install:
- pip install -r requirements.txt
script:
- nosetests
deploy:
  provider: heroku
  api_key:
    secure: bPk7Y6AvTIvNUCn1kTTcgiSOmmQYRCTQZGJ1NwEJXGhhGpMi9wX6meP7e/cuD+W9uBITIvAi5BzKN5741++z9jQuI0ajAlEKIBmJCexjqQYhZWjkaiEQ40SOUHDBRkUwjUJfgKF6hLzfHL5iQphH+1wSyiVbtsh/sB8N+NUa6meCaqywiBbhVXxBcHqPmpQok3KywpkzyTPOHVyHc1ZC3/RSvydwVY05cBhvbHEcMduVr3Kcsa4MZg+Nr2Dtmqbq2cIDLEbkiC+LvoeAShOrxnJo+VIu7P8Qt+lCuXiAncnQqRbx8EGhLzdue19DM3A5dlIhmevPyC383g7j5Ml4vNaQ0249u5vi/b0TQuAbpGJcnmUQjv8sIRWLJ/7Vrn7YIGzomBoRVsX8Q+ON6J39QYsvOikX1nlqDu71I/IKtWjiXgjcYp852m0HwsqAuUVo5ZAGYO3hmdjH+rNXXpFzNzVbZysJSGOthqi1hGRRTrAyBoR6o3eYUGCXRgCM0qtQp+UgzFlsrKXAI46crdmDxnWGdv1GKmAvmTakx9zu+2cNz2zvasamvQb6wJwgBBI+yImitv33G6BsV7zBax4k9o7VVVooqJPRgnMqC2SI511Vh7poBOYdpxP/WTGCAb7Q9Lv18cyV2vGA/teYA33Hh+KjbOBprX44352Zhp680Jw=
  app: tim-chesterfield-5681
  on:
    repo: danakock/flasktaskr
