# specify language
language:
- python

# specify python version(s)
python:
- '2.7'
- '3.4'

# install dependencies
install:
- pip install -r requirements.txt

# run tests
script:
- nosetests

# deploy!
deploy:
  provider: heroku
  api_key:
    secure: fF/+WdMxK3sDpKKkoiwxbEWFn5tFC5XfDewycHkQsLvGfEYejyQdtf+/nMyD3gbCifBj6CSTT42jYwEpjopMGZrvrwiVFm7VftGjsVl72YDT6NUdp+ozixKCTSdQOPXiWPLtunDYl7hcV5Hgm9Y8cS8nuYvgHO7mH0GkWBsr+sGPeziTfLnDUU0iItmQG2t7sVTDUHm0fwXCa3cyN7rNmRruj9oOAlbsHNXUPit4T8RNEzoiwFTjYFJdxpJE9YdieTho7IRgG9D4PRQPKTzHPWQrzCo9sFbCtgn3tWWUdIJlPXZwmszdLeb7Hl8Y6gW0UyVUQNkdBFrNCJZcqvTSkz0VcT1EO11Uj/1F1f2UVi6od1fnT0cdhlwqgqwEVzrumQpkbl0kPoOfPRSwXHNDkYO2c6dBzsDQceOsgMzC/qfU34m6VLqZmIh0BDPBUs78cLIzXASrIzVC0JOQod+1g8WGoCyOypqw3yt8854LSNUTGZsrEdZtdeYAs/erC+LQtzkHsVVIrku7GWEsSnikPHfGDCm39au5Nq4+wG+Z3ymTVMNmvX9nFiypRlIRyNkiT727XlGR/dx5+hqoFvXzKU4BLIk0+49ViKYO8nw30pIeyIwrM0ikbVr+vJXB6hyZ8AMOXc3WkUE2FoebBHKKWji4RTQ2dtk3f5D3byl2qaA=
  app: flasktaskr
  on:
    branch: master
    python: '3.4'
    repo: danakock/flasktaskr
